Repository RedHatQE/pyhelper-utils, pull requests merged in 2024-04, with the labels that each got.

#8 update readme file
  README.md
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser, approved-myakove

#4 Add ignore_exceptions function
  pyhelper_utils/general.py
  renovate.json
  tests/test_general.py
Labels: verified, size/M, can-be-merged, branch-main, approved-rnetser

#10 tts: Use Any in arg type
  pyhelper_utils/general.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-dbasunag

#6 add run_command
  poetry.lock
  pyhelper_utils/shell.py
  pyproject.toml
  tests/test_shell.py
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser, approved-myakove

#16 Add send_slack_message()
  poetry.lock
  pyhelper_utils/notifications.py
  pyproject.toml
  tests/test_notifications.py
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser

#18 test_notifications: fix timeout in post
  pyhelper_utils/notifications.py
  tests/test_notifications.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#22 ignore-exceptions: log function name in error
  pyhelper_utils/general.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#24 Run any function with support to drop to PDB on exception
  poetry.lock
  pyhelper_utils/runners.py
  pyproject.toml
  tests/test_runners.py
Labels: verified, size/L, can-be-merged, branch-main, approved-rnetser

#28 Add retry_interval argument to ignore_exceptions
  pyhelper_utils/general.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-myakove

#30 Ignore exp get return on error
  pyhelper_utils/general.py
  tests/test_general.py
Labels: verified, size/S, can-be-merged, branch-main, approved-rnetser

#34 Force functions typing, fix missing typing
  .pre-commit-config.yaml
  pyhelper_utils/general.py
  pyhelper_utils/runners.py
  pyhelper_utils/shell.py
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#36 tox: run on python 3.8>=
  pyhelper_utils/shell.py
  tox.ini
Labels: verified, size/XS, can-be-merged, branch-main, approved-rnetser

#14 add run_ssh_command
  README.md
  poetry.lock
  pyhelper_utils/exceptions.py
  pyhelper_utils/shell.py
  pyproject.toml
  tests/test_shell.py
Labels: verified, size/XL, branch-main

#43 Function to convert seconds to human readable time string.
  pyhelper_utils/general.py
  tests/test_general.py
Labels: verified, size/M, can-be-merged, branch-main, approved-rnetser, JIRA:MSINTEROP-908
